Update libccid/debug.h to release 1.5.1
Fix compilation errors:
SmartCardReader/libccid/ifdhandler.c: In function ‘IFDHSetProtocolParameters’:
SmartCardReader/libccid/ifdhandler.c:1085:20: error: suggest explicit braces to avoid ambiguous ‘else’ [-Werror=dangling-else]
 1085 |                 if (ccid_desc->dwFeatures & CCID_CLASS_AUTO_PPS_PROP)
      |                    ^
SmartCardReader/libccid/ifdhandler.c:1131:20: error: suggest explicit braces to avoid ambiguous ‘else’ [-Werror=dangling-else]
 1131 |                 if (ccid_desc->dwFeatures & CCID_CLASS_AUTO_PPS_PROP)
      |                    ^

We need to use the rewrite of the DEBUG_*() macros introduced in
51d90a5e0f1d1d9abc420207b5543ea50707d6c1