Fix unused variable
SmartCardReader/libccid/commands.c:1928:28: error: variable ‘sw2’ set but not used [-Werror=unused-but-set-variable]
 1928 |         unsigned char sw1, sw2;
      |                            ^~~
SmartCardReader/libccid/commands.c:1928:23: error: variable ‘sw1’ set but not used [-Werror=unused-but-set-variable]
 1928 |         unsigned char sw1, sw2;
      |                       ^~~