Remove unused variable
SmartCardReader/CcidDriver.c:500:13: error: variable ‘ccid_slot’ set but not used [-Werror=unused-but-set-variable]
  500 |   CcidDesc *ccid_slot;
      |             ^~~~~~~~~